---
title: "Geography 176A"
author: "[AineRoonan](https://aineroonan.github.io)"
subtitle: 'Lab 05: Rasters and Remote Sensing'
output:
  html_document:
    theme: journal
---

```{r}
library(knitr)
library(raster) # Raster Data handling
library(tidyverse) # Data Manipulation
library(getlandsat) # keyless Landsat data (2013-2017)
library(sf) # Vector data processing
library(mapview) # Rapid Interactive visualization
```

##Question 1
```{r}
palo_and_area = read_csv('../geog176A-daily-exercises/uscities.csv') %>%
  filter(city == 'Palo') %>%
  st_as_sf(coords = c('lng','lat'), crs = 4326) %>%
  st_transform(5070) %>%
  st_buffer(5000) %>%
  st_bbox() %>%
  st_as_sfc()
```

##Question 2
```{r}
###Step 2
floods = read_csv('~/github/geog-176A-labs/data/palo-flood.csv')

files = lsat_scene_files(floods$download_url) %>%
  filter(grepl(paste0('B',1:6,'.TIF$', collapse = '|'), file)) %>%
  arrange(file) %>% 
  pull(file)

###Step 3
st = sapply(files, lsat_image) 

b = stack(st) %>% setNames(paste0('band', 1:6))
area(b)

####Step 3 - What are the dimensions of your stacked image? What is the CRS? What is the cell resolution?
#### The dimensions are 7811 rows,  7861 columns, and 59996291 cells with 6 layers. The assigned CRS  was WGS84 datum, UM. The cell resolution is 30 x 30. 

####Step 4
cropped = palo_and_area %>% 
  st_as_sf() %>% 
  st_transform(crs(b))

bCrop = crop(b, cropped)
area(bCrop)
####The dimensions are 340 rows, 346 columns, and 117640 cells with 6 layers. The assigned CRS was WGS84, UM. The cell resolution is 30 x 30. 
```
## Question 3
```{r}
### Step 1
bands <- bCrop %>% setNames(c('coastal', 'blue', 'green', 'red', 'nir', 'swir'))

#### Natural Color
plotRGB(bands, r = 4, g = 3, b = 2)

#### NIR-R-G (Infared)
plotRGB(bands, r = 5, g = 4, b = 2)

#### NIR-SWIR1-R (false color) 
plotRGB(bands, r = 5, g = 6, b = 4)

#### False color for vegetation and water
plotRGB(bands, r = 5, g = 7, b = 1)

### Step 2

### Natural Color
plotRGB(bands, r = 4, g = 3, b = 2, stretch = 'lin')

#### NIR-R-G (Infared)
plotRGB(bands, r = 5, g = 4, b = 2, stretch = 'hist')

#### NIR-SWIR1-R (false color) 
plotRGB(bands, r = 5, g = 6, b = 4, stretch = 'lin')

#### False color for vegetation and water
plotRGB(bands, r = 5, g = 7, b = 1, stretch = 'hist')

#### The stretch function enhances an image by adjusting brightness, contrast, etc. For example, "lin" and "hist" are used to refer to linear or histogram stretches respectively. Different stretches may emphasize different aspects of the same plot, which will hopefully allow for ease of analysis. For example, when comparing lin and hist stretches for my last plot, false color for vegetation and water, there is a significant difference in the two. As I chose hist, the smaller waterways that split off become significantly easier to view, as the red and blue allows for a larger contrast against the green. 

```
## Question 4
```{r}
### Step 1

ndvi = (bands$nir - bands$red)/(bands$nir + bands$red)
ndwi = (bands$green - bands$nir)/(bands$green + bands$nir)
mndwi = (bands$green - bands$swir)/(bands$green + bands$swir)
wri = (bands$green + bands$red)/(bands$nir + bands$swir)
swi = 1/(sqrt(bands$blue-bands$swir))
stacks <- stack(ndvi, ndwi, mndwi, wri, swi) %>% 
  setNames(c('NDVI', 'NDWI', 'MNDWI', 'WRI', 'SWI'))
plot(stacks, col = colorRampPalette(c("blue", "white", "red"))(256))

#### The basic shape of the waterway is visible in all. The basic outlines of the city is visible to some degree within the first 4, but not in SWI. NDVI and NDWI have a relatively equal split of the three colors, with the water represented mostly by one color and the land areas a split of different colors, whereas MNDWI, WRI, and SWI are mostly just two colors, with the water being one color and the land being different shades, or all one shade (in the case of SWI). 

### Step 2

ndviThreshold = 
  function(x) {ifelse(x<=0,1,0)}
ndwiThreshold = 
  function(x) {ifelse(x>=0,1,0)}
mndwiThreshold = 
  function(x) {ifelse(x>=0,1,0)}
wriThreshold = 
  function(x) {ifelse(x>=1,1,0)}
swiThreshold = 
  function(x) {ifelse(x<=5,1,0)}

ndviFlood = 
  calc(ndvi, ndviThreshold)
ndwiFlood = 
  calc(ndwi, ndwiThreshold)
mndwiFlood = 
  calc(mndwi, mndwiThreshold)
wriFlood = 
  calc(wri, wriThreshold)
swiFlood = 
  calc(swi, swiThreshold)
stackFlood = 
  stack(c(ndviFlood, ndwiFlood, mndwiFlood, wriFlood, swiFlood)) %>% 
  setNames(c('NDVI', 'NDWI', 'MNDWI', 'WRI', 'SWI'))

plot(stackFlood, col = 
       colorRampPalette(c("white","blue"))(256))

sum(is.na(values(ndviFlood)))
sum(is.na(values(ndwiFlood)))
sum(is.na(values(mndwiFlood)))
sum(is.na(values(wriFlood)))
sum(is.na(values(swiFlood)))

values(swiFlood) <- ifelse(is.na(values(swiFlood)), 0, values(swiFlood))

```

## Question 5
```{r}
### Step 1
set.seed(20200900)

### Step 2
values <- getValues(bands)
dim(values)
#### This shows the values are expressed as a matrix of size 117640 by 6. The dimensions of bands were 340 by 346 with 6 layers, 340*246 = 117640, which means the values are stored as individual points as one dimension and the layers as the other. 

values = na.omit(values)

rastClust <- kmeans(values, 12, iter.max = 100)

kmeans_raster = stacks$NDVI
values(kmeans_raster) = rastClust$cluster

plot(kmeans_raster)

### Step 3 
values2 = values(ndwiFlood)
table(values2, values(kmeans_raster)) %>% 
  which.max()
idx = which.max(table1[2,])
thresh = function(x) {ifelse(x == idx, 0, 1)}
flood = calc(kmeans_raster, thresh) 

stackFlood <- addLayer(stackFlood, flood)
names(stackFlood)[6] = "K Means"

plot(stackFlood, col = 
       colorRampPalette(c("white","blue"))(256))

```

## Question 6 
```{r}
### Step 1
kabletable = cellStats(stackFlood, sum)
knitr::kable(kabletable, caption = "Number of Flooded Cells per Image", col.names = c("Number of Cells"))

#### As I have answered before, the resolution is 30x30 and we know the units are meters because of the CRS, so the area is 900 meters. So a single cell has an area of 900 meters squared, so to get the total area, we need to multiply the number of cells by 900. 

kabletable2 = kabletable * 900
knitr::kable(kabletable2, caption = "Area of Flooded Cells (meters squared)", col.names = c("Flooded Area"))
### Step 2
cR <- 
  calc(stackFlood, function(x){sum(x)}) %>% 
  setNames('Flood Uncertainty')

cRp = plot(cR, col = blues9, main = 'Flood Uncertainty') 

values(stackFlood) <- 
  ifelse(values(stackFlood)==0, NA, values(stackFlood))

### Step 3
mapview(cR)

#### Some of the cells are not an even number, as they may 
```



